typography_spectrum: 0.6329672522842884
color:
  brandStrength: 0.5584011869505048
  lightness: 0.04294204339385033
  saturation: 0.32996275066398084
  rhythmicContrast: 0.11947868764400482
  brandColors:
    - '#B0CC99'
    - '#677E52'
    - '#B7CA79'
    - '#F6E8B1'
    - '#89725B'
layout_spectrum: 0.7192361790221184
name: my grid experience
navigation:
  - name: Martha's website
    url: 'http://fletcherstreeturbanridingclub.com/'
    type: external
  - name: Wikipedia article
    url: 'https://en.wikipedia.org/wiki/Fletcher_Street_Urban_Riding_Club'
    type: external
